#!/usr/bin/env python3    
import socket
import sys
import getch # detect if client press '5', need to install this package
import json

msg = [{'src':"yeeeeeeee",'dst':"hahahaha"}]
jmsg = json.dumps(msg)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    Host = socket.gethostbyname(socket.gethostname())
    sock.connect((Host, 10001))
    print("wait for server...")
    print(sock.recv(1024).decode())
    while True:
        key = getch.getch()
        if key == '5':
            print("success!")
            sock.send('5'.encode())
            sock.recv(1024).decode()
            break
        else:
            print("pleas press '5'")
    
    while True:
        data = input("> ")
        if data.strip() == "":
            break
        else:
            sock.send(data.encode())
            print (sock.recv(1024).decode())
            sock.send("finish one transit".encode())
            print (sock.recv(1024).decode())
        '''
        else:
            sock.sendall(jmsg.encode())
            print (sock.recv(1024).decode())
        '''

    sock.close()
