#!/usr/bin/env python3
import socketserver
from time import ctime
import socket
import sys
from termios import tcflush, TCIFLUSH

current_client = []
max_client_count = 3

class MyRequestHandler(socketserver.BaseRequestHandler):
    def setup(self):
        global current_client
        current_client.append(self.request)
        print('a user connect, IP:',self.client_address)
        if len(current_client) >= max_client_count:
            tcflush(sys.stdin, TCIFLUSH)
            signal = input("All users are connected. Wait forsignal (type any key and \"enter\" or \"enter\" only): ")
            message = "press 5 to continue"
            for s in current_client:
                s.sendall(bytes(message,"utf-8"))
            
            current_client.clear()
        
    def handle(self):
        # print('connect from ', self.client_address)
        while True:
            data = self.request.recv(1024).strip().decode()
            if not data:  # If client disconnect data will be None
                break
            else:
                print("client say:", data)
                self.request.sendall(('[%s] %s' % (ctime(), data)).encode())
        self.request.close()
    def finish(self):
        print('A user diconnect.')

class ThreadingTCPSserver(socketserver.ThreadingMixIn, socketserver.TCPServer):
    daemon_threads = True        # kill all of the thread when get any exceptions
    allow_reuse_address = True   # avoid some error when reboot the server
    pass

if __name__ == "__main__":
    # HOST, PORT = '127.0.0.1', 10001
    HOST = socket.gethostbyname(socket.gethostname())   # check current IP address
    PORT = 10001
    ADDRESS = (HOST,PORT)
    try:
        with ThreadingTCPSserver(ADDRESS,MyRequestHandler) as server:
            print('waiting for connection')
            server.serve_forever()
    except KeyboardInterrupt:
        print("\ncaught keyboard interrupt, exiting")
        server.shutdown()
        server.server_close()
    except ConnectionResetError:
        print("client already close! can't send!")
