#!/usr/bin/env python3
from stop_view import Ui_MainWindow as Ui_stop
from ui import Ui_MainWindow as Ui_play
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import *
from ast import literal_eval
import random
import socket
import select
import getch # detect if client press '5', need to install this package
import json
import time
import sys

class MainWindow(QMainWindow):
  def __init__(self, sock, parent=None):
    super(MainWindow, self).__init__(parent)
    self.mode_dic = {'init': 1, 'start':2, 'stop':3, 'alloc':4, 'wait':5}
    self.mode = 1
    self.my_id = 0
    self.other_id = 3
    self.recv_data = 0
    self.sock = sock
    self.my_result = -1
    self.other_result = -1
    self.first_in_alloc = True
#### time
    self.start_t = 0
    self.end_t = 0
    self.timer_start = QTimer(self)
    self.timer_start.timeout.connect(self.set_start_view)
    self.timer_stop = QTimer(self)
    self.timer_stop.timeout.connect(self.set_stop_view)
    self.timer_alloc = QTimer(self)
    self.timer_alloc.timeout.connect(self.set_alloc_view)
    self.timer_group = QTimer(self)
    self.timer_group.timeout.connect(self.set_group_view)
    self.timer_result = QTimer(self)
    self.timer_result.timeout.connect(self.set_alloc_re_view)
#### UI
    self.QtStack = QtWidgets.QStackedLayout()
    self.screen = QDesktopWidget().screenGeometry ()
    self.showFullScreen()
    self.Ui_setup()
    self.ConnectToServer(5)
    self.my_id = int(self.recv_data)
    self.left_id, self.right_id = self.get_id(self.my_id)
    self.set_id(self.my_id)

  def ConnectToServer(self, data):
    print("send data: ", data)
    self.sock.send(str(data).encode())
    self.recv_data = self.sock.recv(1024).decode()
    print("receive data :" + self.recv_data)

  def Ui_setup(self):
    try:
      self.show()
      self.mode = self.mode_dic['init']
      self.start_view = Ui_play()
      self.start_view.setupUi(self)
      self.stop_view = Ui_stop()
      self.stop_view.setupUi(self)
      self.stop_view.label.setText("Press 5")
      #self.setCentralWidget(self.stop_view.centralwidget)
      self.start_view.centralwidget.resize(self.screen.width(),self.screen.height())
      self.stop_view.centralwidget.resize(self.screen.width(),self.screen.height())
      self.QtStack.addWidget(self.start_view.centralwidget)
      self.QtStack.addWidget(self.stop_view.centralwidget)
      self.QtStack.setCurrentIndex(1)

    except Exception as e:
       print(e)

  def set_start_view(self):
    self.recv_data = self.sock.recv(1024).decode()
    print("receive data:", self.recv_data)
    print("########## In start view")
    src_list = str_to_list(self.recv_data)
    self.set_src(self.my_id, src_list)
    self.mode = self.mode_dic['start']
    self.mask_alloc()
    self.QtStack.setCurrentIndex(0)

  def set_stop_view(self):
    self.timer_stop.stop()
    if self.mode == self.mode_dic['alloc']:
      self.first_in_alloc = True
     # self.mode = self.mode_dic['stop']
      alloc_result = [0,0,0]
      alloc_result[self.my_id-1] = self.my_result
      alloc_result[self.other_id-1] = self.other_result
      print("alloc_result: ", alloc_result)
      self.ConnectToServer(alloc_result)
      self.set_timer(self.timer_result, 2)
    print("########## In stop view")
    self.mode = self.mode_dic['stop']
    self.stop_view.label.setText("+")
    self.QtStack.setCurrentIndex(1)

  def set_wait_view(self):
    print("########## In wait view")
    self.mode = self.mode_dic['wait']
    self.stop_view.label.setText("Wait")
    self.QtStack.setCurrentIndex(1)

  def set_alloc_view(self):
    self.timer_alloc.stop()
    print("########## In alloc view")
    self.mode = self.mode_dic['alloc']
    self.mask_alloc()
    #FIXME the bigger one can alloc
    my_src = random.randint(0,11)
    self.init_alloc_view(my_src)
    other_src = 11 - my_src
    if self.my_id%3+1 == self.other_id:
      self.start_view.src_3.setText(str(other_src))
      other_src = int(self.start_view.src_3.text())
    else:
      self.start_view.src_1.setText(str(other_src))
      other_src = int(self.start_view.src_1.text())

    #exec("self.start_view.%s.setText(\"%d\")" % (alloc_name, other_src) )
    self.QtStack.setCurrentIndex(0)
    if self.first_in_alloc == True:
      self.first_in_alloc = False
      self.set_timer(self.timer_stop, 4)

  def set_group_view(self):
    self.timer_group.stop()
    self.mode = self.mode_dic['wait']
    print("########## In group view")
    print("group_view recv data: ", self.recv_data )
    re_list = str_to_list(self.recv_data)
    self.start_view.alloc_1.setText(str(re_list[self.left_id-1]))
    self.start_view.alloc_2.setText(str(re_list[self.my_id-1]))
    self.start_view.alloc_3.setText(str(re_list[self.right_id-1]))
    self.QtStack.setCurrentIndex(0)
    self.set_timer(self.timer_stop, 2)
    self.set_timer(self.timer_alloc, 4)

  def set_alloc_re_view(self):
    print("receive data:", self.recv_data)
    print("########## In allocate result view")
    src_list = str_to_list(self.recv_data)
    self.set_src(self.my_id, src_list)
    self.mode = self.mode_dic['wait']
    self.mask_alloc()
    self.QtStack.setCurrentIndex(0)
    self.set_timer(self.timer_start, 2)

  def keyPressEvent(self, event):
    assert(self.my_id != self.other_id), "my id is the same to other id. "
    key = event.key()
    if key == QtCore.Qt.Key_Escape:
      self.showNormal()
    elif self.mode == self.mode_dic['init'] and key == QtCore.Qt.Key_5:
      print("press 5")
      #self.set_wait_view()
      self.start_t = time.time()
      self.set_start_view()
    elif self.mode == self.mode_dic['start']:
      select_id = -1
      if key == QtCore.Qt.Key_2:
        select_id = self.right_id
      elif key == QtCore.Qt.Key_1:
        select_id = self.left_id
      self.ConnectToServer(select_id)
      self.end_t = time.time()
      self.set_stop_view()
      self.set_timer(self.timer_group, 5 - (self.end_t - self.start_t))
    elif self.mode == self.mode_dic['alloc'] and key == QtCore.Qt.Key_1:
      self.alloc_src(self.my_id, self.other_id, -1)
    elif self.mode == self.mode_dic['alloc'] and key == QtCore.Qt.Key_2:
      self.alloc_src(self.my_id, self.other_id, 1)

  def set_id(self, my_id):
    # my_id : int
    id = [1, 2 ,3]
    my_id -= 1
    self.start_view.pos_2.setText("ID : " + str(id[my_id]))
    self.start_view.pos_3.setText("ID : " + str(id[(my_id+1)%3]))
    self.start_view.pos_1.setText("ID : " + str(id[(my_id+2)%3]))
    QApplication.processEvents()

  def set_src(self, my_id, src_list):
    # my_id : int, src_list : int list
    my_id -= 1
    self.start_view.src_2.setText(str(src_list[my_id]))
    self.start_view.src_3.setText(str(src_list[(my_id+1)%3]))
    self.start_view.src_1.setText(str(src_list[(my_id+2)%3]))
    QApplication.processEvents()

  def alloc_src(self, my_id, other_id, add_minus):
    my_src = int(self.start_view.src_2.text())
    if my_src == 0 and add_minus == -1:
      return
    if my_id%3+1 == other_id:
      other_src = int(self.start_view.src_3.text())
      if other_src == 0 and add_minus == 1:
        return
      self.other_result = other_src - add_minus
      self.start_view.src_3.setText(str(self.other_result))
    else:
      other_src = int(self.start_view.src_1.text())
      if other_src == 0 and add_minus == 1:
        return
      self.other_result = other_src - add_minus
      self.start_view.src_1.setText(str(self.other_result))

    self.my_result = my_src + add_minus
    self.start_view.src_2.setText(str(self.my_result))
    self.setCentralWidget(self.start_view.centralwidget)

  def set_timer(self, timer, wait_time):
    timer.start(round(wait_time * 1000))

  def get_id(self, my_id):
    my_id -= 1
    id = [1, 2 ,3]
    left_id = id[(my_id+2)%3]
    right_id = id[(my_id+1)%3]
    return left_id, right_id

  def mask_alloc(self):
    self.start_view.alloc_1.setText("")
    self.start_view.alloc_2.setText("")
    self.start_view.alloc_3.setText("")

  def init_alloc_view(self, my_src):
    self.start_view.src_1.setText("")
    self.start_view.src_2.setText(str(my_src))
    self.start_view.src_3.setText("")
    self.start_view.src_1.setStyleSheet("color : gray;")
    self.start_view.src_3.setStyleSheet("color : gray;")

#########

def ui_setup(sock):
  app = QApplication(sys.argv)
  window = MainWindow(sock)
  window.show()
  sys.exit(app.exec_())
  return app, window

def str_to_list(str_data):
  try:
    print("str_to_list:",str_data)
    return literal_eval(str_data)
  except Exception as e:
     print(e)

def main():
  msg = [{'src':"yeeeeeeee",'dst':"hahahaha"}]
  jmsg = json.dumps(msg)
  TimeOut = 10

  with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    Host = socket.gethostbyname(socket.gethostname())
    #Host = "10.3.207.113"
    print("Host:",Host)
    sock.connect((Host, 10001))
    print("wait for server...")
    print(sock.recv(1024).decode())
    #while True:

    app, window = ui_setup(sock)

    while True:
      print("> ", end='', flush=True)
      inputStart = time.time()
      i, o, e = select.select( [sys.stdin], [], [], TimeOut )
      if i:
        inputEnd = time.time()
        print("you spend ", inputEnd - inputStart, " second on input")
        data = sys.stdin.readline().strip()
        if data == "":
          break

        sock.send(data.encode())
        print (sock.recv(1024).decode())
        sock.send("finish one transit".encode())
        print (sock.recv(1024).decode())
      else:
        print("\nYou miss one trail!")
        data = "One client miss a trail!"
        sock.send(data.encode())
        print(sock.recv(1024).decode())
        sock.send("all clients jump to the next trail".encode())
        print(sock.recv(1024).decode())

    sock.close()

if __name__ == "__main__":
  main()
