#!/usr/bin/env python3
from socketserver import TCPServer
from socketserver import StreamRequestHandler
from socketserver import ThreadingMixIn
from time import ctime

# First, you must create a request handler class by subclassing the BaseRequestHandler class 
# and overriding its handle() method
class MyRequestHandler(StreamRequestHandler):
    def handle(self):
        print('connect form ', self.client_address)
        data = self.rfile.readline().strip().decode()
        print(data)
        self.wfile.write(('[%s] %s' % (ctime(), data)).encode())
    
    def finish(self):
        print('A user diconnect.')

class ThreadingTCPSserver(ThreadingMixIn, TCPServer):
    pass


# with socketserver.TCPServer((HOST, PORT), MyTCPHandler) as server:
if __name__ == "__main__":
    HOST, PORT = '127.0.0.1', 10001
    ADDRESS = (HOST,PORT)
    try:
        # Second, you must instantiate one of the server classes, 
        # passing it the server’s address and the request handler class.
        with ThreadingTCPSserver(ADDRESS,MyRequestHandler) as server:
            print('waiting for connection')
            server.serve_forever()
    except KeyboardInterrupt:
        print("\ncaught keyboard interrupt, exiting")

