# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setGeometry(QtCore.QRect(0, 0, 900, 150))
        self.top.setStyleSheet("QFrame{ background-color : black}\n"
"")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.left = QtWidgets.QFrame(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(0, 150, 300, 350))
        self.left.setStyleSheet("QFrame{ background-color : #FEBE4F}\n"
"")
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.pos_1 = QtWidgets.QLabel(self.left)
        self.pos_1.setGeometry(QtCore.QRect(100, 220, 110, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pos_1.setFont(font)
        self.pos_1.setAutoFillBackground(False)
        self.pos_1.setStyleSheet("color : black;")
        self.pos_1.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_1.setObjectName("pos_1")
        self.src_1 = QtWidgets.QLabel(self.left)
        self.src_1.setGeometry(QtCore.QRect(130, 30, 60, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.src_1.setFont(font)
        self.src_1.setStyleSheet("color : black;")
        self.src_1.setText("")
        self.src_1.setAlignment(QtCore.Qt.AlignCenter)
        self.src_1.setObjectName("src_1")
        self.mid = QtWidgets.QFrame(self.centralwidget)
        self.mid.setGeometry(QtCore.QRect(300, 150, 300, 350))
        self.mid.setStyleSheet("QFrame{ background-color : #00B8B8}\n"
"")
        self.mid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid.setObjectName("mid")
        self.pos_2 = QtWidgets.QLabel(self.mid)
        self.pos_2.setGeometry(QtCore.QRect(100, 220, 110, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pos_2.setFont(font)
        self.pos_2.setAutoFillBackground(False)
        self.pos_2.setStyleSheet("color : black;")
        self.pos_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_2.setObjectName("pos_2")
        self.src_2 = QtWidgets.QLabel(self.mid)
        self.src_2.setGeometry(QtCore.QRect(130, 30, 60, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.src_2.setFont(font)
        self.src_2.setStyleSheet("color : black;")
        self.src_2.setText("")
        self.src_2.setAlignment(QtCore.Qt.AlignCenter)
        self.src_2.setObjectName("src_2")
        self.right = QtWidgets.QFrame(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(600, 150, 300, 350))
        self.right.setStyleSheet("QFrame{ background-color : #FF6E6E}\n"
"")
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.pos_3 = QtWidgets.QLabel(self.right)
        self.pos_3.setGeometry(QtCore.QRect(100, 220, 110, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pos_3.setFont(font)
        self.pos_3.setStyleSheet("color : black;")
        self.pos_3.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_3.setObjectName("pos_3")
        self.src_3 = QtWidgets.QLabel(self.right)
        self.src_3.setGeometry(QtCore.QRect(140, 40, 60, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.src_3.setFont(font)
        self.src_3.setStyleSheet("color : black;")
        self.src_3.setText("")
        self.src_3.setAlignment(QtCore.Qt.AlignCenter)
        self.src_3.setObjectName("src_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pos_1.setText(_translate("MainWindow", "ID : 1"))
        self.pos_2.setText(_translate("MainWindow", "ID : 2"))
        self.pos_3.setText(_translate("MainWindow", "ID : 3"))


